/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const ProjectIDLazyRouteImport = createFileRoute('/$projectID')()

const ProjectIDLazyRoute = ProjectIDLazyRouteImport.update({
  id: '/$projectID',
  path: '/$projectID',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$projectID.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectID': typeof ProjectIDLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectID': typeof ProjectIDLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectID': typeof ProjectIDLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$projectID'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$projectID'
  id: '__root__' | '/' | '/$projectID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIDLazyRoute: typeof ProjectIDLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$projectID': {
      id: '/$projectID'
      path: '/$projectID'
      fullPath: '/$projectID'
      preLoaderRoute: typeof ProjectIDLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIDLazyRoute: ProjectIDLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
